name: 'Minio Upload and Discord webhook'
description: 'Upload to Minio Storage and send notification to Discord.'
author: 'Jan Sitarski'
inputs:
  endpoint:
    description: 'Minio endpoint of object storage host'
    required: true
  access_key:
    description: 'Minio access key (username)'
    required: true
  secret_key:
    description: 'Minio secret key (password)'
    required: true
  bucket:
    description: 'Set the target minio bucket for deployment.'
    required: true
  source_file:
    description: 'Set an input directory for deployment.'
    required: false
    default: 'public'
  target_dir:
    description: 'Set a target directory for deployment (with a leading slash).'
    required: false
    default: '/'
  webhook:
    description: 'Set Discord webhook address.'
    required: false
    default: 'error'
  webhook_title:
    description: 'Set webhook title to show in channel.'
    required: false
    default: 'MinIO upload'
  webhook_desc:
    description: "Set webhook content."
    required: false
    default: "Uploaded ${{ github.event.inputs.source_file }} to ${{ github.event.inputs.bucket }} bucket"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MINIO_ENDPOINT: ${{ inputs.endpoint }}
    MINIO_ACCESS_KEY: ${{ inputs.access_key }}
    MINIO_SECRET_KEY: ${{ inputs.secret_key }}
    WEBHOOK_URL: ${{ inputs.webhook }}
    WEBHOOK_TITLE: ${{ inputs.webhook_title }}
    WEBHOOK_DESC: ${{ inputs.webhook_desc }}
  args:
    - ${{ inputs.source_file }}
    - '${{ inputs.bucket }}${{ inputs.target_dir }}'

branding:
  icon: 'upload-cloud'
  color: 'purple'
